default_platform(:ios)

platform :ios do
  desc "Running all unit tests"
  lane :unit_tests do
    scan(
      scheme: "WalletTests",
      device: "iPhone 13 Pro"
    )
  end

  desc "Running UI tests"
  lane :ui_tests do
    scan(
      scheme: "WalletUITests",
      device: "iPhone 13 Pro"
    )
  end

end
