name: unit/ui tests 

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Unit & UI Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Running unit tests
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: unit_tests
     
      - name: Running UI tests
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: ui_tests